# step-9 model preparation

In [ ]:
import pandas as pd
df = pd.read_csv('/content/processed_dataset.csv')
df

s4.loc.ic.ins.p1  s8.mbl.p2  s7.s4.day.no.mou.p2.p4  s3.new.rev.p3  \
0                     3      -0.72                1.000000           7.16   
1                     3      -0.08                0.500000           4.43   
2                     3      -0.09                0.384615           4.43   
3                     4       1.04                0.416667           4.43   
4                     4      -0.04                0.222222           5.12   
...                 ...        ...                     ...            ...   
24995                 4       0.76                0.250000           4.43   
24996                 4       0.37                0.454545           8.77   
24997                 3      -0.79                0.100000           4.48   
24998                 4      -1.09               99.000000          13.06   
24999                 4       0.00                0.400000           4.43   

       s7.s5.s4.day.nomou.p4  s8.ic.mou.all.p3  target  s7.rev.p2.p6  \
0                   0.500000             -0.29       1          0.09   
1                   0.500000              0.00       1          0.09   
2                   0.384615             -0.29       1          0.09   
3                   0.250000             -0.29       0          0.09   
4                   0.500000             -0.29       0          0.09   
...                      ...               ...     ...           ...   
24995               0.375000              0.21       1          0.24   
24996               0.500000              0.04       0          0.23   
24997               0.333333              0.21       0          0.19   
24998               0.000000             -0.29       0          0.24   
24999               0.333333              0.21       1          0.09   

       ds.usg.p6  ds.og.usg.p4  s8.rtd.mou.p3  s7.rtd.mou.m1.m2  s8.rev.p6  \
0              0             0          -0.40          0.552297      -0.12   
1              0             0          -0.11          0.552297      -0.15   
2              0             0          -0.39          0.552297      -0.07   
3              0             0          -0.02          1.176028      -0.15   
4              0             0          -0.40          1.176028       0.01   
...          ...           ...            ...               ...        ...   
24995          0             0          -0.13          1.176028      -0.14   
24996          0             0           0.22          0.688912       0.05   
24997          0             0           0.23          1.176028      -0.03   
24998          0             0          -0.40          0.579099       0.12   
24999          0             0           0.00          1.176028      -0.15   

       s4.rch.val.gt.30.p2  s4.low.blnc.ins.p2  s4.loc.ins.l14  \
0                        0                   4              13   
1                        0                   4              13   
2                        0                   4              14   
3                        0                   3              14   
4                        0                   0              14   
...                    ...                 ...             ...   
24995                    0                   2              13   
24996                    0                   4              13   
24997                    0                   3              13   
24998                    1                   0              14   
24999                    0                   4              14   

       s4.data.ins.l14  s3.og.rev.all.m2  prop.loc.i2i.mou.og.mou.p3  
0                    0            6.0200                    0.609456  
1                    0            4.2075                    0.716538  
2                    0            4.3300                    0.699592  
3                    0            4.2075                    0.251304  
4                    2            4.2075                    0.683105  
...                ...               ...                     

In [ ]:
X = df.drop('target', axis=1)
y = df['target']

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [ ]:
# Assume you have features (X) and target variable (y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Without hyperparameter tuning Logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
y_pred = log_reg.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_train, log_reg.predict(X_train)))
log_reg_acc = accuracy_score(y_test, log_reg.predict(X_test))
print(log_reg_acc)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


0.76555
0.7656
[[3074  363]
 [ 809  754]]
              precision    recall  f1-score   support

           0       0.79      0.89      0.84      3437
           1       0.68      0.48      0.56      1563

    accuracy                           0.77      5000
   macro avg       0.73      0.69      0.70      5000
weighted avg       0.76      0.77      0.75      5000



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# Without hyperparameter tuning Decision Tree classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
y_pred = dt_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Decision Tree Classifier Accuracy: {accuracy:.3f}")
print(f"Decision Tree Classifier Precision: {precision:.3f}")
print(f"Decision Tree Classifier Recall: {recall:.3f}")
print(f"Decision Tree Classifier F1-score: {f1:.3f}")

Decision Tree Classifier Accuracy: 0.698
Decision Tree Classifier Precision: 0.516
Decision Tree Classifier Recall: 0.535
Decision Tree Classifier F1-score: 0.525


# Without hyperparameter tuning Random forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(random_state=42)

rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Random Forest Accuracy: {accuracy:.3f}")
print(f"Random Forest Precision: {precision:.3f}")
print(f"Random Forest Recall: {recall:.3f}")
print(f"Random Forest F1-score: {f1:.3f}")

Random Forest Accuracy: 0.784
Random Forest Precision: 0.716
Random Forest Recall: 0.512
Random Forest F1-score: 0.598


# With Random search hyperparameter tuning logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import numpy as np
lr = LogisticRegression(random_state=42)
param_distributions = {
    'C': np.logspace(-4, 4, 20),
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear', 'saga']
}
random_search = RandomizedSearchCV(lr, param_distributions=param_distributions,
                                   n_iter=20, cv=3, scoring='accuracy', n_jobs=-1, random_state=42)
random_search.fit(X_train, y_train)
print("Best hyperparameters: ", random_search.best_params_)
print("Best score: ", random_search.best_score_)
best_model = random_search.best_estimator_
y_pred = best_model.predict(X_test)

# Calculate evaluation metrics on the test set
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1-score: ", f1)

Best hyperparameters:  {'solver': 'liblinear', 'penalty': 'l1', 'C': 1.623776739188721}
Best score:  0.7775999813870692
Accuracy:  0.781
Precision:  0.7729358642821534
Recall:  0.781
F1-score:  0.77282717262233


# With Random search hyperparameter tuning Decision tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import numpy as np
dt = DecisionTreeClassifier(random_state=42)
param_distributions = {
    'max_depth': [2, 4, 6, 8, 10, None],
    'min_samples_split': [2, 5, 10],
    'criterion': ['gini', 'entropy']
}

random_search = RandomizedSearchCV(dt, param_distributions=param_distributions,
                                   n_iter=20, cv=3, scoring='accuracy', n_jobs=-1, random_state=42)
random_search.fit(X_train, y_train)

# Print the best hyperparameters and the corresponding score
print("Best hyperparameters: ", random_search.best_params_)
print("Best score on cross-validation: ", random_search.best_score_)

# Get the best model
best_model = random_search.best_estimator_

# Calculate metrics for the training set
y_train_pred = best_model.predict(X_train)
train_accuracy = accuracy_score(y_train, y_train_pred)
train_precision = precision_score(y_train, y_train_pred, average='weighted')
train_recall = recall_score(y_train, y_train_pred, average='weighted')
train_f1 = f1_score(y_train, y_train_pred, average='weighted')
train_confusion_matrix = confusion_matrix(y_train, y_train_pred)

print("\nTraining Set Metrics:")
print("Accuracy: ", train_accuracy)
print("Precision: ", train_precision)
print("Recall: ", train_recall)
print("F1-score: ", train_f1)
print("Confusion Matrix:\n", train_confusion_matrix)

# Calculate metrics for the test set
y_test_pred = best_model.predict(X_test)
test_accuracy = accuracy_score(y_test, y_test_pred)
test_precision = precision_score(y_test, y_test_pred, average='weighted')
test_recall = recall_score(y_test, y_test_pred, average='weighted')
test_f1 = f1_score(y_test, y_test_pred, average='weighted')
test_confusion_matrix = confusion_matrix(y_test, y_test_pred)

print("\nTest Set Metrics:")
print("Accuracy: ", test_accuracy)
print("Precision: ", test_precision)
print("Recall: ", test_recall)
print("F1-score: ", test_f1)
print("Confusion Matrix:\n", test_confusion_matrix)

Best hyperparameters:  {'min_samples_split': 10, 'max_depth': 6, 'criterion': 'gini'}
Best score on cross-validation:  0.7682996588244394

Training Set Metrics:
Accuracy:  0.78385
Precision:  0.7765672085233873
Recall:  0.78385
F1-score:  0.7761053299888598
Confusion Matrix:
 [[12159  1487]
 [ 2836  3518]]

Test Set Metrics:
Accuracy:  0.7768
Precision:  0.768246757477908
Recall:  0.7768
F1-score:  0.7681363715568662
Confusion Matrix:
 [[3054  383]
 [ 733  830]]


# With Random search hyperparameter tuning RandomForest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import numpy as np


# Create a Random Forest Classifier object
rf = RandomForestClassifier(random_state=42)

# Set the parameter distributions for RandomizedSearchCV
param_distributions = {
    'n_estimators': np.arange(100, 501, 50),
    'max_depth': [4, 6, 8, 10, None],
    'min_samples_split': [2, 5, 10],
    'criterion': ['gini', 'entropy']
}

# Create a RandomizedSearchCV object and fit it to the data
random_search = RandomizedSearchCV(rf, param_distributions=param_distributions,
                                   n_iter=20, cv=3, scoring='accuracy', n_jobs=-1, random_state=42)
random_search.fit(X, y)

# Print the best hyperparameters and the corresponding score
print("Best hyperparameters: ", random_search.best_params_)


# Use the best model to make predictions
best_model = random_search.best_estimator_
y_pred = best_model.predict(X)

# Calculate evaluation metrics
accuracy = accuracy_score(y, y_pred)
precision = precision_score(y, y_pred, average='weighted')
recall = recall_score(y, y_pred, average='weighted')
f1 = f1_score(y, y_pred, average='weighted')

print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1-score: ", f1)

Best hyperparameters:  {'n_estimators': 350, 'min_samples_split': 10, 'max_depth': 10, 'criterion': 'gini'}
Accuracy:  0.83676
Precision:  0.8351186943288589
Recall:  0.83676
F1-score:  0.829771775135056
